#!/usr/bin/env python
"""
eventloop script - demo piety and eventloop modules
"""
import piety # includes from eventloop import *

def task0(): print 'task 0'
def task1(): print 'task 1'

def main():
    # Here timeout, done, run are all imported by piety from eventloop
    t0 = piety.Task(name='task 0', handler=task0, input=piety.timer)
    t1 = piety.Task(name='task 1', handler=task1, input=piety.timer)
    piety.done = False # reset, might be resuming after quit() 
    piety.run(nevents=10) # handle 10 clock ticks and exit
    piety.tasks() # show the tasks

if __name__ == '__main__':
    main()
