#!/usr/bin/env python
"""
piety - Run pysh shell, ed and edd editors in a Session under Piety scheduler
 Use command and key modules instead of Python raw_input to get command line.
 This script is named piety (with no file type) so no name clash with piety.py

To demonstrate the shell and editors:

  $ piety
 pysh shell, type any Python statement, exit() or Ctrl-D to exit
 >> console.run(ed)   # run the ed line editor
 ...
 q                     # exit ed, return to pysh Python shell
 >> console.run(edd)  # run the edd display editor
 ...
 q
 >> exit()             # exit from pysh Python shell
 $                     # back to host shell

To exit, then resume the piety session in a single Python session use python -i :

 $ python -i piety
 ...
 >> exit()             # exit from pysh Python shell
 >>>                   # back to host Python shell
 >>> main()            # restart piety script
 >>                    # back to pysh Python shell
 ...

To create, start, pause, resume a Piety task from the shell:

 ...
 >> w0 = writer.Writer(fname='w0.txt')
 >> t0 = piety.Task(name='w0',handler=w0.write,event=piety.timeout,enabled=piety.true)
 ... in another terminal window, tail -f w0.txt shows writer is writing to w0.txt
 >> piety.tasks()
 ... shows console and writer tasks 
 >> t0.enabled = piety.false
 ... w0.txt stops growing
 >> t0.enabled = piety.true
 ... w0.txt resumes growing

This script demonstrates how a different keyboard reader can be
selected for each terminal job.  This script configures the shell and
display editor jobs using the input reader from the key module, so
these jobs can use some keys that send multi-character control
sequences (such the four keyboard arrow keys in the lower right corner
of the MacBook Pro keyboard).  The line editor is configured with the
default reader that just handles single-character keycodes, so it
cannot use those arrow keys, but it can use the alternatives ^F ^B ^N
^P which send single-character codes.
"""

import sys
import piety, session, job, command, keyboard, key

# rename modules so we can use original module names as command names
import pysh as _pysh, ed as _ed, edd as _edd

# Session, a terminal task
console = session.Session(name='console', event=sys.stdin)

# Python shell

def pysh_startup():
    _pysh.pexit = False # enable pysh event loop, compare to Job stopped= below

pyshc = command.Command(prompt='>> ', reader=key.Key(),  handler=_pysh.mk_shell())
pysh = job.Job(session=console, application=pyshc, startup=pysh_startup, 
               # Enable exit on >> exit() or >> ^D
               stopped=(lambda: _pysh.pexit or pyshc.command == keyboard.C_d), 
               cleanup=piety.quit)

# line editor

def ed_startup():
    _ed.quit = False # enable event loop, compare to Job( stopped=...) arg below

ed = job.Job(session=console,
             application=command.Command(prompt='', handler=_ed.cmd),
             startup=ed_startup, stopped=(lambda: _ed.quit))
              
# display editor

def edd_startup():
    _edd.ed.quit = False # enable event loop, compare to Job( stopped=..) arg below
    _edd.init_display()

edd = job.Job(session=console, 
               application=
               command.Command(prompt='', reader=key.Key(), handler=_edd.cmd),
               startup=edd_startup, 
               stopped=(lambda: _edd.ed.quit), 
               cleanup=_edd.restore_display)

def main():
    """
    Run Python REPL and applications using pysh shell in a Session
    """
    pysh() # start the first job
    piety.done = False # reset, might be resuming after pysh.pexit(), piety.quit()
    piety.run() # start event loop, continue until pysh >> exit()

if __name__ == '__main__':
    main()
