#!/usr/bin/env python
"""
piety - Uses the Piety scheduler to run the console session with
  three jobs created by console_tasks, concurrently with the two
  writer tasks created by writer_tasks.

See console_tasks header for directions on how to run the console jobs.
See writer_tasks header for drections on how to observe the writer tasks.
"""

import piety

# Writer tasks in writer_tasks module don't appear explicitly here - 
# they are referenced by the piety.schedule data structure used by piety.run
import writer_tasks

# Likewise, console jobs and session are referenced in console_tasks.jobs,
# and the session is also referenced in piety.schedule
# Must import identifiers used below and in pysh shell
# It seems pysh shell command line sees same scope as code in this module
from console_tasks import jobs, edc, edd

def main():
    """
    Run the console session and writer tasks concurrently under the Piety scheduler.
    """
    jobs.pysh() # start the first job, recall pysh is in jobs namespace
    piety.done = False # reset, might be resuming after pysh.pexit(), piety.quit()
    piety.run() # start event loop, continue until pysh >> exit()

if __name__ == '__main__':
    main()
