#!/usr/bin/env python
"""
pyshc.py - Run a pysh Python shell session.
          Use console and key modules instead of
           Python raw_input to get command line as in pysh.py main.  
          BUT do not use Piety scheduler.
"""

import pysh, console, key, line, terminal

# define before use in pyshc = ... below

quit = False

def q():
    'Call this function to exit from the shell'
    global quit
    quit = True

# Here the optional initialize and cleanup args are default None
pyshc = console.Console(prompt='>> ', command=pysh.mk_shell(), 
                       optional_keymap=line.keymap, quit=q) 

k = key.Key(pyshc.handle_key)

def main():
    # terminal setup and restore are done for each command 
    #  by pyshc.do_command via k.getchar
    # BUT initial pyshc() is needed here.
    global quit
    quit = False
    pyshc() # calls terminal.setup()
    console.Console.continues = True
    while not quit:
        key = k.getchar() # calls pyshc.handle_key
    # quit handled by pyshc.pause called by pyshc.handle_key via k.getchar
    terminal.restore()

if __name__ == '__main__':
    main()
