#!/usr/bin/env python
"""
session - run several jobs in a session, but without Piety scheduler.
 
Similar to piety script EXCEPT no Piety scheduler - just uses ordinary while loop.
No piety scheduler, so this runs terminal jobs only; there are no writer tasks.
"""

# console jobs and session are referenced in console_tasks.jobs,
# Must import identifiers used below and in pysh shell
# It seems pysh shell command line sees same scope as code in this module
from console_tasks import console, jobs, pysh, edc, edd

def main():
    """
    Run Python REPL and applications using pysh shell in a Session
    """
    jobs.pysh() # start the first job
    # No Piety scheduler - instead just use an ordinary while loop 
    while not pysh.pexit: # pysh module here, not jobs.pysh
        console.handler()  # block waiting for each single character 

if __name__ == '__main__':
    main()
