#!/usr/bin/env python
"""
printing - demo Command with keymap modified to support printing terminal
           Handler just echoes command line, type command 'q' to exit.
"""

import command
from keyboard import bs, delete, C_a, C_b, C_d, C_e, C_f, C_k

c = command.Command(handler=command.echo)

# remove from keymap those keys whose functions require a display terminal
for k in (C_a, C_b, C_d, C_e, C_f, C_k):
    del c.keymap[k]

# reassign backspace and delete to use printing terminal version
c.keymap[delete] = c.keymap[bs] = c.backward_delete_last_char

def main():
    command.quit = False    # typing command 'q' sets quit = True
    while not command.quit: # now C_d is disabled, ^D exit doesn't work
        if c.new_command:
            c.restart()
        c.reader()

if __name__ == '__main__':
    main()
